### ISSUE TITLE
Improve import_rawdata()

### ISSUE THREAD

**Issue by hsonne** [KWB-R/kwb.umberto#4]
Improve the following section of `import_rawdata()` in order to avoid this:
```
Error in rbind(deparse.level, ...) : 
  Anzahl der Spalten der Argumente unterschiedlich
```

Code section:
```
for (csv_file in csv_files) {
  print(sprintf("Importing csv file '%s'", csv_file))
  tmp <- read_input(csv_file, ...) %>% janitor::clean_names()
  if (csv_file == csv_files[1]) {
    rawdata <- tmp
  }
  else {
    rawdata <- rbind(rawdata, tmp)
  }
}
```

Suggestions:

* Check if columns differ and give a good message about it.
* Use lapply and `dplyr::bind_rows()`

**Comment by mrustl** [comment]
@hsonne
Gab's Probleme bei Lea? Wenn ja wieso? UMBERTO sollte doch immer die gleiche Spaltenanzahl rausgeben ausser wenn es Probleme beim Einlesen gibt wenn eine Datei mit ; und eine andere mit "," als Seperator exportiert wurde

**Comment by hsonne** [comment]
@mrustl Lea hat irgend etwas anders gemacht beim Export, so dass der Output unterschiedlich war. Sie hat das behoben. Nichtsdestotrotz wäre eine klare Fehlermeldung "Spalten unterscheiden sich, Spalten in Datei 1: ..., Spalten in Datei 2: ..." schön.
